#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

readonly script_name="bm"
readonly version="0.1.0"
readonly emoji=📁

function usage() {

    # TODO Handle the other options
    cat <<USAGE_TEXT
A command-line utility for bookmarks.

Usage: ${script_name} [option] [<argument>]

OPTIONS:
-h, --help              Print this usage information
-v, --version           Print the ${script_name} version

These are common bm commands used in various situations:
    add                 Adds new link
    category            Creates and lists the categories
    delete              Deletes the bookmark
    list                Lists the all bookmarks
    remove              Removes the category

For bug reporting and contributions, please see:
<https://github.com/gozeloglu/bm>
USAGE_TEXT
}

if (( $# == 0 )); then 
  usage
  exit 1
fi 

case "$1" in 
  add)
    "${PWD}/commands/add.sh" "$@"
    shift
    ;;
  delete)
    "${PWD}/commands/delete.sh" "$@"
    shift
    ;;
  remove)
    "${PWD}/commands/remove.sh" "$@"
    shift
    ;;
  list)
    "${PWD}/commands/list.sh" "$@"
    shift
    ;;
  setup)
    "${PWD}/commands/setup.sh"
    shift
    ;;
  --help | -h)
    usage
    shift
    ;;
  --version | -v)
    echo "bm $(cat ${PWD}/VERSION)"
    shift
    ;;
  *)
    echo "Invalid Command"
    echo "See '${script_name} --help'."
    ;;
esac
